=== RomRaider/assembla.flat/tags/0.4.0/logger.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT byte ( #PCDATA ) >

<!ELEMENT address ( byte+ ) >

<!ELEMENT ref EMPTY >
<!ATTLIST ref id IDREF #REQUIRED >

<!ELEMENT depends ( ref+ ) >

<!ELEMENT conversion EMPTY >
<!ATTLIST conversion expr CDATA #REQUIRED >
<!ATTLIST conversion format ( 0 | 0.0 | 0.00 ) #REQUIRED >
<!ATTLIST conversion units CDATA #REQUIRED >

<!ELEMENT conversions ( conversion+ ) >

<!ELEMENT parameter ( ( address | depends ), conversions ) >
<!ATTLIST parameter desc CDATA #REQUIRED >
<!ATTLIST parameter name CDATA #REQUIRED >
<!ATTLIST parameter id ID #REQUIRED >

<!ELEMENT parameters ( parameter+ ) >

<!ELEMENT switch EMPTY >
<!ATTLIST switch filelogcontroller ( yes | no ) #IMPLIED >
<!ATTLIST switch bit ( 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 ) #REQUIRED >
<!ATTLIST switch byte CDATA #REQUIRED >
<!ATTLIST switch desc CDATA #REQUIRED >
<!ATTLIST switch name CDATA #REQUIRED >
<!ATTLIST switch id ID #REQUIRED >

<!ELEMENT switches ( switch+ ) >

<!ELEMENT protocol ( parameters*, switches* ) >
<!ATTLIST protocol id ID #REQUIRED >

<!ELEMENT protocols ( protocol+ ) >

<!ELEMENT logger ( protocols ) >

=== RomRaider/assembla.flat/tags/0.4.0/logger.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE logger SYSTEM "logger.dtd">

<logger>
    <protocols>
        <protocol id="SSM">
            <parameters>

                <parameter id="P1" name="Engine Load" desc="">
                    <address>
                        <byte>0x000007</byte>
                    </address>
                    <conversions>
                        <conversion units="%" expr="x*100/255" format="0.00"/>
                    </conversions>
                </parameter>

                <parameter id="P2" name="Coolant Temperature" desc="">
                    <address>
                        <byte>0x000008</byte>
                    </address>
                    <conversions>
                        <conversion units="C" expr="x-40" format="0"/>
                        <conversion units="F" expr="32+9*(x-40)/5" format="0"/>
                    </conversions>
                </parameter>

                <parameter id="P3" name="Air/Fuel Correction #1" desc="">
                    <address>
                        <byte>0x000009</byte>
                    </address>
                    <conversions>
                        <conversion units="%" expr="(x-128)*100/128" format="0.00"/>
                    </conversions>
                </parameter>

                <parameter id="P4" name="Air/Fuel Learning #1" desc="">
                    <address>
                        <byte>0x00000A</byte>
                    </address>
                    <conversions>
                        <conversion units="%" expr="(x-128)*100/128" format="0.00"/>
                    </conversions>
                </parameter>

                <parameter id="P5" name="Air/Fuel Correction #2" desc="">
                    <address>
                        <byte>0x00000B</byte>
                    </address>
                    <conversions>
                        <conversion units="%" expr="(x-128)*100/128" format="0.00"/>
                    </conversions>
                </parameter>

                <parameter id="P6" name="Air/Fuel Learning #2" desc="">
                    <address>
                        <byte>0x00000C</byte>
                    </address>
                    <conversions>
                        <conversion units="%" expr="(x-128)*100/128" format="0.00"/>
                    </conversions>
                </parameter>

                <parameter id="P7" name="Manifold Absolute Pressure" desc="">
                    <address>
                        <byte>0x00000D</byte>
                    </address>
                    <conversions>
                        <conversion units="psi" expr="x*37/255" format="0.00"/>
                        <conversion units="bar" expr="x*37/255/14.50377" format="0.00"/>
                    </conversions>
                </parameter>

                <parameter id="P8" name="Engine Speed" desc="">
                    <address>
                        <byte>0x00000E</byte>
                        <byte>0x00000F</byte>
                    </address>
                    <conversions>
                        <conversion units="rpm" expr="x/4" format="0"/>
                    </conversions>
                </parameter>

                <parameter id="P9" name="Vehicle Speed" desc="">
                    <address>
                        <byte>0x000010</byte>
                    </address>
                    <conversions>
                        <conversion units="km/h" expr="x" format="0.0"/>
                        <conversion units="mph" expr="x*0.621371192" format="0.0"/>
                    </conversions>
                </parameter>

                <parameter id="P10" name="Ignition Timing" desc="">
                    <address>
                        <byte>0x000011</byte>
                    </address>
                    <conversions>
                        <conversion units="degrees" expr="(x-128)/2" format="0.0"/>
                    </conversions>
                </parameter>

                <parameter id="P11" name="Intake Air Temperature" desc="">
                    <address>
                        <byte>0x000012</byte>
                    </address>
                    <conversions>
                        <conversion units="C" expr="x-40" format="0"/>
                        <conversion units="F" expr="32+9*(x-40)/5" format="0"/>
                    </conversions>
                </parameter>

                <parameter id="P12" name="Mass Air Flow" desc="">
                    <address>
                        <byte>0x000013</byte>
                        <byte>0x000014</byte>
                    </address>
                    <conversions>
                        <conversion units="gram/s" expr="x/100" format="0.00"/>
                    </conversions>
                </parameter>

                <parameter id="P13" name="Throttle Opening Angle" desc="Engine throttle opening angle.">
                    <address>
                        <byte>0x000015</byte>
                    </address>
                    <conversions>
                        <conversion units="%" expr="x*100/255" format="0.0"/>
                    </conversions>
                </parameter>

                <parameter id="P14" name="Front O2 Sensor #1" desc="">
                    <address>
                        <byte>0x000016</byte>
                        <byte>0x000017</byte>
                    </address>
                    <conversions>
                        <conversion units="V" expr="x/200" format="0.0"/>
                    </conversions>
                </parameter>

                <parameter id="P15" name="Rear O2 Sensor" desc="">
                    <address>
                        <byte>0x000018</byte>
                        <byte>0x000019</byte>
                    </address>
                    <conversions>
                        <conversion units="V" expr="x/200" format="0.0"/>
                    </conversions>
                </parameter>

                <parameter id="P16" name="Front O2 Sensor #2" desc="">
                    <address>
                        <byte>0x00001A</byte>
                        <byte>0x00001B</byte>
                    </address>
                    <conversions>
                        <conversion units="V" expr="x/200" format="0.0"/>
                    </conversions>
                </parameter>

                <parameter id="P17" name="Battery Voltage" desc="">
                    <address>
                        <byte>0x00001C</byte>
                    </address>
                    <conversions>
                        <conversion units="V" expr="x*8/100" format="0.00"/>
                    </conversions>
                </parameter>

                <parameter id="P18" name="Mass Air Flow Sensor Voltage" desc="">
                    <address>
                        <byte>0x00001D</byte>
                    </address>
                    <conversions>
                        <conversion units="V" expr="x/50" format="0.00"/>
                    </conversions>
                </parameter>

                <parameter id="P19" name="Throttle Sensor Voltage" desc="">
                    <address>
                        <byte>0x00001E</byte>
                    </address>
                    <conversions>
                        <conversion units="V" expr="x/50" format="0.00"/>
                    </conversions>
                </parameter>

                <parameter id="P20" name="Differential Pressure Sensor Voltage" desc="">
                    <address>
                        <byte>0x00001F</byte>
                    </address>
                    <conversions>
                        <conversion units="V" expr="x/50" format="0.00"/>
                    </conversions>
                </parameter>

                <parameter id="P21" name="Fuel Injector #1 Pulse Width" desc="">
                    <address>
                        <byte>0x000020</byte>
                    </address>
                    <conversions>
                        <conversion units="ms" expr="x*256/1000" format="0.00"/>
                    </conversions>
                </parameter>

                <parameter id="P22" name="Fuel Injector #2 Pulse Width" desc="">
                    <address>
                        <byte>0x000021</byte>
                    </address>
                    <conversions>
                        <conversion units="ms" expr="x*256/1000" format="0.00"/>
                    </conversions>
                </parameter>

                <parameter id="P23" name="Knock Correction" desc="">
                    <address>
                        <byte>0x000022</byte>
                    </address>
                    <conversions>
                        <conversion units="degrees" expr="(x-128)/2" format="0.0"/>
                    </conversions>
                </parameter>

                <parameter id="P24" name="Atmospheric Pressure" desc="">
                    <address>
                        <byte>0x000023</byte>
                    </address>
                    <conversions>
                        <conversion units="psi" expr="x*37/255" format="0.00"/>
                        <conversion units="bar" expr="x*37/255/14.50377" format="0.00"/>
                    </conversions>
                </parameter>

                <parameter id="P25" name="Manifold Relative Pressure" desc="">
                    <address>
                        <byte>0x000024</byte>
                    </address>
                    <conversions>
                        <conversion units="psi" expr="(x-128)*37/255" format="0.00"/>
